
CREATE TABLE ANSWER
(
  ANSWER    VARCHAR(500) NOT NULL COMMENT '설문 답변',
  ANSWER_ID VARCHAR(50)  NOT NULL COMMENT '답변ID',
  PRIMARY KEY (ANSWER_ID)
) COMMENT '답변';

CREATE TABLE QUESTION
(
  QUESTION    VARCHAR(500) NOT NULL COMMENT '설문 문항',
  QUESTION_ID VARCHAR(50)  NOT NULL COMMENT '문항ID',
  PRIMARY KEY (QUESTION_ID)
) COMMENT '문항';

CREATE TABLE STATISTICS
(
  ANSWER_ID   VARCHAR(50) NOT NULL COMMENT '답변ID',
  QUESTION_ID VARCHAR(50) NOT NULL COMMENT '문항ID',
  USER_ID     VARCHAR(50) NOT NULL COMMENT '참여자ID'
) COMMENT '통계';

CREATE TABLE USER
(
  USER    VARCHAR(50) NOT NULL COMMENT '설문참여자',
  USER_ID VARCHAR(50) NOT NULL COMMENT '참여자ID',
  PRIMARY KEY (USER_ID)
) COMMENT '참여자';

ALTER TABLE STATISTICS
  ADD CONSTRAINT FK_ANSWER_TO_STATISTICS
    FOREIGN KEY (ANSWER_ID)
    REFERENCES ANSWER (ANSWER_ID);

ALTER TABLE STATISTICS
  ADD CONSTRAINT FK_QUESTION_TO_STATISTICS
    FOREIGN KEY (QUESTION_ID)
    REFERENCES QUESTION (QUESTION_ID);

ALTER TABLE STATISTICS
  ADD CONSTRAINT FK_USER_TO_STATISTICS
    FOREIGN KEY (USER_ID)
    REFERENCES USER (USER_ID);
